# Starter pipeline

trigger:
- master

pr:
- master

variables:
  solutionPath: StoreApp

jobs:
- job: build_linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: dotnet build -c Release
    displayName: dotnet build
    workingDirectory: $(solutionPath)
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: 'test'
      projects: '$(solutionPath)'
      arguments: '-c Release'
      testRunTitle: 'ubuntu'

  - script: dotnet publish -c Release -o ../publish
    displayName: dotnet publish
    workingDirectory: $(solutionPath)

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1(1f2ea6cb-77bc-4002-a917-07ca87ead705)'
      appType: 'webApp'
      WebAppName: 'nFuntanillaProject1'
      packageForLinux: '$(System.DefaultWorkingDirectory)/publish'

  
