# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

jobs:
- job: build_linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: dotnet build
    displayName: dotnet build
    workingDirectory: StoreApp

- job: build_windows
  pool:
    vmImage: windows-latest
    
  steps:
  - task: NuGetToolInstaller@1
    displayName: install nuget
    inputs:
      versionSpec: 
  - task: NuGetCommand@2
    displayName: NuGetRestore
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
  - task: VSBuild@1
    displayName: Visual Studio Build
    inputs:
      solution: '**\*.sln'
      platform: 'Any CPU'
      configuration: 'Release'
  - task: VSTest@2
    displayName: Run Tests
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\*test*.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'