# Starter pipeline

trigger:
- master

pr:
- master

variables:
  solutionPath: StoreApp

jobs:
- job: build_linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: SonarCloudPrepare@1
    displayName: sonarcloud prepare analysis
    inputs:
      SonarCloud: 'sonarcloud nfuntanilla'
      organization: '2006-jun15-net'
      scannerMode: 'MSBuild'
      projectKey: '2006-jun15-net_noah-project1'
      projectName: 'Noah project 1 StoreApp'

  - script: dotnet build -c Release
    displayName: dotnet build
    workingDirectory: $(solutionPath)

  - task: SonarCloudAnalyze@1
    displayName: sonarcloud run analysis

  - task: SonarCloudPublish@1
    displayName: sonarcloud publish
    inputs:
      pollingTimeoutSec: '300'

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: 'test'
      arguments: '-c Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
      publishTestResults: true
      projects: '$(solutionPath)/StoreApp.Test/*.csproj'
      testRunTitle: 'ubuntu'
      
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage report'
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'

  - script: dotnet publish -c Release -o ../publish
    displayName: dotnet publish
    workingDirectory: $(solutionPath)

  - task: AzureRmWebAppDeployment@4
    displayName: deploy to Azure App Service
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1(1f2ea6cb-77bc-4002-a917-07ca87ead705)'
      appType: 'webApp'
      WebAppName: 'nFuntanillaProject1'
      packageForLinux: '$(System.DefaultWorkingDirectory)/publish'

  
